server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
#  静态路由
#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh #payment_route 路由的ID 没有固定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
#          predicates:
#            - Path=/provider/payment/ok/**  #断言,路径相匹配的进行路由
#
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/provider/payment/circuit/**

# 动态路由
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route 路由的ID 没有固定规则但要求唯一,建议配合服务名
          uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT  #匹配后提供服务的路由地址
          predicates:
            - Path=/provider/payment/ok/**  #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://CLOUD-PROVIDER-HYSTRIX-PAYMENT
          predicates:
            - Path=/provider/payment/circuit/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
